# Generated by Django 4.0.4 on 2022-05-11 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
    ]
