# Generated by Django 4.0.4 on 2022-05-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rat', '0002_remove_question_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_name', models.TextField()),
                ('paper_description', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
    ]
